"""fix column lengths

Revision ID: b7e01f9fe1cf
Revises: 
Create Date: 2026-04-11 15:38:39.359644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e01f9fe1cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('stipend',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('deadline',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internships', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.String(length=255),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('stipend',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
